### PR TITLE
Improve performance

### PR DESCRIPTION
**Pull request by behnammodi**
Keeping `arguments.length` in variable

### CODE REVIEW

**Comment by dcousens** [comment]
@behnammodi can you show profiling that this is significantly faster?

**Comment by behnammodi** [comment]
@dcousens Sure, you can see it here [Profiling](https://perf.link/#eyJpZCI6IjlodnYzNGJ5a240IiwidGl0bGUiOiIxIGlzIE1hc3RlciBhbmQgMiBpcyBteSBQUiIsImJlZm9yZSI6InZhciBoYXNPd24gPSB7fS5oYXNPd25Qcm9wZXJ0eTtcblxuZnVuY3Rpb24gY2xhc3NOYW1lczEoKSB7XG4gIHZhciBjbGFzc2VzID0gW107XG5cbiAgZm9yICh2YXIgaSA9IDA7IGkgPCBhcmd1bWVudHMubGVuZ3RoOyBpKyspIHtcbiAgICB2YXIgYXJnID0gYXJndW1lbnRzW2ldO1xuICAgIGlmICghYXJnKSBjb250aW51ZTtcblxuICAgIHZhciBhcmdUeXBlID0gdHlwZW9mIGFyZztcblxuICAgIGlmIChhcmdUeXBlID09PSAnc3RyaW5nJyB8fCBhcmdUeXBlID09PSAnbnVtYmVyJykge1xuICAgICAgY2xhc3Nlcy5wdXNoKGFyZyk7XG4gICAgfSBlbHNlIGlmIChBcnJheS5pc0FycmF5KGFyZykpIHtcbiAgICAgIGlmKGFyZy5sZW5ndGgpIHtcbiAgICAgICAgdmFyIGlubmVyID0gY2xhc3NOYW1lcy5hcHBseShudWxsLCBhcmcpO1xuICAgICAgICBpZiAoaW5uZXIpIHtcbiAgICAgICAgICBjbGFzc2VzLnB1c2goaW5uZXIpO1xuICAgICAgICB9XG4gICAgICB9XG4gICAgfSBlbHNlIGlmIChhcmdUeXBlID09PSAnb2JqZWN0Jykge1xuICAgICAgaWYgKGFyZy50b1N0cmluZyAhPT0gT2JqZWN0LnByb3RvdHlwZS50b1N0cmluZykge1xuICAgICAgICBjbGFzc2VzLnB1c2goYXJnLnRvU3RyaW5nKCkpO1xuICAgICAgfSBlbHNlIHtcbiAgICAgICAgZm9yICh2YXIga2V5IGluIGFyZykge1xuICAgICAgICAgIGlmIChoYXNPd24uY2FsbChhcmcsIGtleSkgJiYgYXJnW2tleV0pIHtcbiAgICAgICAgICAgIGNsYXNzZXMucHVzaChrZXkpO1xuICAgICAgICAgIH1cbiAgICAgICAgfVxuICAgICAgfVxuICAgIH1cbiAgfVxuXG4gIHJldHVybiBjbGFzc2VzLmpvaW4oJyAnKTtcbn1cblxuZnVuY3Rpb24gY2xhc3NOYW1lczIoKSB7XG4gIHZhciBjbGFzc2VzID0gW107XG5cbiAgZm9yICh2YXIgaSA9IDAsIGxlbmd0aD1hcmd1bWVudHMubGVuZ3RoOyBpIDwgbGVuZ3RoOyBpKyspIHtcbiAgICB2YXIgYXJnID0gYXJndW1lbnRzW2ldO1xuICAgIGlmICghYXJnKSBjb250aW51ZTtcblxuICAgIHZhciBhcmdUeXBlID0gdHlwZW9mIGFyZztcblxuICAgIGlmIChhcmdUeXBlID09PSAnc3RyaW5nJyB8fCBhcmdUeXBlID09PSAnbnVtYmVyJykge1xuICAgICAgY2xhc3Nlcy5wdXNoKGFyZyk7XG4gICAgfSBlbHNlIGlmIChBcnJheS5pc0FycmF5KGFyZykpIHtcbiAgICAgIGlmKGFyZy5sZW5ndGgpIHtcbiAgICAgICAgdmFyIGlubmVyID0gY2xhc3NOYW1lcy5hcHBseShudWxsLCBhcmcpO1xuICAgICAgICBpZiAoaW5uZXIpIHtcbiAgICAgICAgICBjbGFzc2VzLnB1c2goaW5uZXIpO1xuICAgICAgICB9XG4gICAgICB9XG4gICAgfSBlbHNlIGlmIChhcmdUeXBlID09PSAnb2JqZWN0Jykge1xuICAgICAgaWYgKGFyZy50b1N0cmluZyAhPT0gT2JqZWN0LnByb3RvdHlwZS50b1N0cmluZykge1xuICAgICAgICBjbGFzc2VzLnB1c2goYXJnLnRvU3RyaW5nKCkpO1xuICAgICAgfSBlbHNlIHtcbiAgICAgICAgZm9yICh2YXIga2V5IGluIGFyZykge1xuICAgICAgICAgIGlmIChoYXNPd24uY2FsbChhcmcsIGtleSkgJiYgYXJnW2tleV0pIHtcbiAgICAgICAgICAgIGNsYXNzZXMucHVzaChrZXkpO1xuICAgICAgICAgIH1cbiAgICAgICAgfVxuICAgICAgfVxuICAgIH1cbiAgfVxuXG4gIHJldHVybiBjbGFzc2VzLmpvaW4oJyAnKTtcbn0iLCJ0ZXN0cyI6W3sibmFtZSI6IlRlc3QgQ2FzZSIsImNvZGUiOiJjbGFzc05hbWVzMShudWxsLCBmYWxzZSwgJ2JhcicsIHVuZGVmaW5lZCwgMCwgMSwgeyBiYXo6IG51bGwgfSwgJycsJ2ZvbycsIHsgYmFyOiB0cnVlLCBkdWNrOiBmYWxzZSB9LCAnYmF6JywgeyBxdXV4OiB0cnVlIH0sbnVsbCwgZmFsc2UsICdiYXInLCB1bmRlZmluZWQsIDAsIDEsIHsgYmF6OiBudWxsIH0sICcnLCdmb28nLCB7IGJhcjogdHJ1ZSwgZHVjazogZmFsc2UgfSwgJ2JheicsIHsgcXV1eDogdHJ1ZSB9LG51bGwsIGZhbHNlLCAnYmFyJywgdW5kZWZpbmVkLCAwLCAxLCB7IGJhejogbnVsbCB9LCAnJywnZm9vJywgeyBiYXI6IHRydWUsIGR1Y2s6IGZhbHNlIH0sICdiYXonLCB7IHF1dXg6IHRydWUgfSxudWxsLCBmYWxzZSwgJ2JhcicsIHVuZGVmaW5lZCwgMCwgMSwgeyBiYXo6IG51bGwgfSwgJycsJ2ZvbycsIHsgYmFyOiB0cnVlLCBkdWNrOiBmYWxzZSB9LCAnYmF6JywgeyBxdXV4OiB0cnVlIH0sbnVsbCwgZmFsc2UsICdiYXInLCB1bmRlZmluZWQsIDAsIDEsIHsgYmF6OiBudWxsIH0sICcnLCdmb28nLCB7IGJhcjogdHJ1ZSwgZHVjazogZmFsc2UgfSwgJ2JheicsIHsgcXV1eDogdHJ1ZSB9LG51bGwsIGZhbHNlLCAnYmFyJywgdW5kZWZpbmVkLCAwLCAxLCB7IGJhejogbnVsbCB9LCAnJywnZm9vJywgeyBiYXI6IHRydWUsIGR1Y2s6IGZhbHNlIH0sICdiYXonLCB7IHF1dXg6IHRydWUgfSxudWxsLCBmYWxzZSwgJ2JhcicsIHVuZGVmaW5lZCwgMCwgMSwgeyBiYXo6IG51bGwgfSwgJycsJ2ZvbycsIHsgYmFyOiB0cnVlLCBkdWNrOiBmYWxzZSB9LCAnYmF6JywgeyBxdXV4OiB0cnVlIH0sbnVsbCwgZmFsc2UsICdiYXInLCB1bmRlZmluZWQsIDAsIDEsIHsgYmF6OiBudWxsIH0sICcnLCdmb28nLCB7IGJhcjogdHJ1ZSwgZHVjazogZmFsc2UgfSwgJ2JheicsIHsgcXV1eDogdHJ1ZSB9LG51bGwsIGZhbHNlLCAnYmFyJywgdW5kZWZpbmVkLCAwLCAxLCB7IGJhejogbnVsbCB9LCAnJywnZm9vJywgeyBiYXI6IHRydWUsIGR1Y2s6IGZhbHNlIH0sICdiYXonLCB7IHF1dXg6IHRydWUgfSk7IiwicnVucyI6WzIxMDAwLDE5MDAwLDE4MDAwLDcwMDAsNTAwMCwzNjAwMCwxOTAwMCwyMDAwMCwxODAwMCwyNTAwMCwxMDAwLDIxMDAwLDIwMDAsNDkwMDAsMTAwMCw3MDAwLDIxMDAwLDIxMDAwLDQwMDAwLDkwMDAsMjUwMDAsMjgwMDAsNjAwMCwxMDAwLDIzMDAwLDI5MDAwLDMxMDAwLDEwMDAsNDAwMCw1NDAwMCw0OTAwMCw0NzAwMCwxMDAwLDQyMDAwLDQ5MDAwLDM5MDAwLDE2MDAwLDI2MDAwLDM5MDAwLDEwMDAsMzgwMDAsMTYwMDAsMjAwMDAsMjAwMCwyODAwMCwxNTAwMCw1MTAwMCwxOTAwMCw1NTAwMCwxMDAwLDQwMDAsNDYwMDAsMzAwMDAsMzkwMDAsNTIwMDAsMjgwMDAsOTAwMCwzMDAwLDM2MDAwLDEwMDAsMzMwMDAsNDEwMDAsMTUwMDAsNTAwMCwxODAwMCw0NDAwMCw1MDAwLDIxMDAwLDEwMDAsMTcwMDAsNTAwMCw0NzAwMCwxMDAwMCwxNzAwMCwxMDAwLDE2MDAwLDUwMDAsNDAwMCwzMTAwMCwxOTAwMCw0MzAwMCw0MzAwMCw0NjAwMCw1MDAwLDM2MDAwLDIwMDAsNDkwMDAsMjgwMDAsMTAwMCwxNTAwMCw1MDAwLDQ3MDAwLDUwMDAsMjUwMDAsMzkwMDAsNTUwMDAsODAwMCw1NTAwMCwxMzAwMCw0MTAwMF0sIm9wcyI6MjI4MDB9LHsibmFtZSI6IlRlc3QgQ2FzZSIsImNvZGUiOiJjbGFzc05hbWVzMihudWxsLCBmYWxzZSwgJ2JhcicsIHVuZGVmaW5lZCwgMCwgMSwgeyBiYXo6IG51bGwgfSwgJycsJ2ZvbycsIHsgYmFyOiB0cnVlLCBkdWNrOiBmYWxzZSB9LCAnYmF6JywgeyBxdXV4OiB0cnVlIH0sbnVsbCwgZmFsc2UsICdiYXInLCB1bmRlZmluZWQsIDAsIDEsIHsgYmF6OiBudWxsIH0sICcnLCdmb28nLCB7IGJhcjogdHJ1ZSwgZHVjazogZmFsc2UgfSwgJ2JheicsIHsgcXV1eDogdHJ1ZSB9LG51bGwsIGZhbHNlLCAnYmFyJywgdW5kZWZpbmVkLCAwLCAxLCB7IGJhejogbnVsbCB9LCAnJywnZm9vJywgeyBiYXI6IHRydWUsIGR1Y2s6IGZhbHNlIH0sICdiYXonLCB7IHF1dXg6IHRydWUgfSxudWxsLCBmYWxzZSwgJ2JhcicsIHVuZGVmaW5lZCwgMCwgMSwgeyBiYXo6IG51bGwgfSwgJycsJ2ZvbycsIHsgYmFyOiB0cnVlLCBkdWNrOiBmYWxzZSB9LCAnYmF6JywgeyBxdXV4OiB0cnVlIH0sbnVsbCwgZmFsc2UsICdiYXInLCB1bmRlZmluZWQsIDAsIDEsIHsgYmF6OiBudWxsIH0sICcnLCdmb28nLCB7IGJhcjogdHJ1ZSwgZHVjazogZmFsc2UgfSwgJ2JheicsIHsgcXV1eDogdHJ1ZSB9LG51bGwsIGZhbHNlLCAnYmFyJywgdW5kZWZpbmVkLCAwLCAxLCB7IGJhejogbnVsbCB9LCAnJywnZm9vJywgeyBiYXI6IHRydWUsIGR1Y2s6IGZhbHNlIH0sICdiYXonLCB7IHF1dXg6IHRydWUgfSxudWxsLCBmYWxzZSwgJ2JhcicsIHVuZGVmaW5lZCwgMCwgMSwgeyBiYXo6IG51bGwgfSwgJycsJ2ZvbycsIHsgYmFyOiB0cnVlLCBkdWNrOiBmYWxzZSB9LCAnYmF6JywgeyBxdXV4OiB0cnVlIH0sbnVsbCwgZmFsc2UsICdiYXInLCB1bmRlZmluZWQsIDAsIDEsIHsgYmF6OiBudWxsIH0sICcnLCdmb28nLCB7IGJhcjogdHJ1ZSwgZHVjazogZmFsc2UgfSwgJ2JheicsIHsgcXV1eDogdHJ1ZSB9LG51bGwsIGZhbHNlLCAnYmFyJywgdW5kZWZpbmVkLCAwLCAxLCB7IGJhejogbnVsbCB9LCAnJywnZm9vJywgeyBiYXI6IHRydWUsIGR1Y2s6IGZhbHNlIH0sICdiYXonLCB7IHF1dXg6IHRydWUgfSk7IiwicnVucyI6WzQ0MDAwLDIwMDAwLDQwMDAwLDcwMDAsMjcwMDAsNDkwMDAsNDMwMDAsMzIwMDAsMTkwMDAsMjMwMDAsODAwMCw0MDAwLDI1MDAwLDU2MDAwLDMyMDAwLDI4MDAwLDQyMDAwLDEwMDAsMzIwMDAsMTAwMCw1MDAwLDQzMDAwLDM2MDAwLDEwMDAsNDQwMDAsMTkwMDAsNDgwMDAsMTgwMDAsNDIwMDAsNDIwMDAsMTMwMDAsMTAwMCwxMDAwLDIwMDAsMTIwMDAsNTYwMDAsMjYwMDAsMzcwMDAsMzYwMDAsMjEwMDAsMTAwMDAsMTAwMCwxMjAwMCw5MDAwLDI5MDAwLDE1MDAwLDUzMDAwLDEyMDAwLDI3MDAwLDQwMDAsMjAwMCwzODAwMCwxMDAwLDM0MDAwLDE2MDAwLDM2MDAwLDI2MDAwLDI0MDAwLDIxMDAwLDIzMDAwLDEzMDAwLDU1MDAwLDM0MDAwLDM3MDAwLDI2MDAwLDkwMDAsMTkwMDAsNTYwMDAsMjYwMDAsMTIwMDAsNTYwMDAsNTEwMDAsNTYwMDAsNDcwMDAsNTEwMDAsODAwMCwzOTAwMCw3MDAwLDEyMDAwLDI3MDAwLDU2MDAwLDE0MDAwLDUwMDAwLDQwMDAwLDYwMDAsNDEwMDAsMTAwMCwyMDAwMCw1MjAwMCwzODAwMCw1NDAwMCwzOTAwMCw0MzAwMCwzODAwMCw0MTAwMCw4MDAwLDEyMDAwLDQ4MDAwLDQyMDAwLDQwMDBdLCJvcHMiOjI3MTcwfV0sInVwZGF0ZWQiOiIyMDIwLTExLTA5VDA3OjQ1OjM3LjMzOFoifQ%3D%3D)

**Comment by dcousens** [comment]
There is significant difference between these solutions in my measurements and in using your linked tool.

**Comment by behnammodi** [comment]
@dcousens I use Chrome, but we have the same result in Chrome and Firefox

**Comment by dcousens** [comment]
Unfortunately,  I cannot reproduce this.  Sorry @behnammodi!

**Comment by behnammodi** [comment]
@dcousens Ok

**Pull request closed without merging**
