### PR TITLE
ES Module Export

### LINKED ISSUE #99: [Question] is it possible to have separate ES modules exports
Hello.

I am building most of my frontend libs with rollupjs and single non-convertable library is this one. Is it possible to have a separate version with es2015 modules exports? I can create PR if you tell me your preference about handling and support.

Thanks.

### PR DESCRIPTION
**Pull request by jedmao**
Fixes #99 

See https://github.com/JedWatson/classnames/issues/99#issuecomment-266185918

### CODE REVIEW

**Comment by dcousens** [comment]
concept ACK,  ping @JedWatson

**Comment by jedmao** [comment]
@dcousens fixed!

**Comment by jedmao** [comment]
@JedWatson please refer to #106, which demonstrates the problem and proves this PR fixes it. Thank you!

**Comment by aldendaniels** [comment]
👍 Just ran into this using `classnames` in TypeScript

**Comment by ebenoist** [comment]
Can this please be merged? Its a simple fix and helps folks out who are using typescript.

**Comment by zemd** [comment]
just made a quick port of this lib with custom builds for es6 and others https://github.com/zemd/classnames2

**Comment by kingcoconut** [comment]
Can we please have this merged

**Comment by kingcoconut** [comment]
@dcousens are you able to merge?

**Comment by dcousens** [comment]
I can merge,  I can't release.

**Comment by octatone** [comment]
Is this module abandoned?

**Comment by dcousens** [comment]
@JedWatson ?

**Comment by jedmao** [comment]
I published `@jedmao/classnames`, version 2.2.6 to fix this issue, if anyone is interested. Please note that this is my own scoped package and I am not the original author of this repo.

**Comment by iki** [comment]
@JedWatson any way to release it? It's a breaker when using https://sucrase.io/ for fast transpile of typescript.

**Comment by JedWatson** [comment]
Sure, sorry for the delay. I'll sort this out and get a new version published.

**Comment by JedWatson** [comment]
Done

**Comment by dcousens** [comment]
@JedWatson :tada:

**Pull request merged**
