### PR TITLE
Safer `hasOwnProperty` check

### PR DESCRIPTION
**Pull request by impinball**

### CODE REVIEW

**Comment by dcousens** [comment]
@impinball could you split the polyfill to another PR?
It may be a breaking change for some unfortunately so we'd have to bump major to adhere to SEMVER, so I'd prefer to separate the discussion.

**Comment by dcousens** [comment]
Wait nevermind,  there is already a polyfill requirement for <= IE8.

**Comment by dcousens** [comment]
@impinball `Object.keys` may be slower,  so I'll have to bench it.

**Comment by impinball** [comment]
@dcousens Slower if you're using the polyfill. It's actually implemented significantly faster in every other case for objects in both V8 and SpiderMonkey.

**Comment by impinball** [comment]
It is slower in SpiderMonkey, though. But it simplified things.

**Comment by dcousens** [comment]
For others,  this PR was merged as "safer" as shown in a comment by @impinball:

> object.hasOwnProperty(prop) > {}.hasOwnProperty.call(object, prop) somehow...Not smart if someone uses hasOwnProperty as a class name. Even worse if user input isn't sanitized first, and parsed into a class name. Oops.

Ref: https://github.com/lhorie/mithril.js/issues/545#issuecomment-144072682

**Comment by impinball** [comment]
Thanks for cross posting. I didn't intend to sound like an asshole (although I know I did).

**Comment by dcousens** [comment]
@impinball

> It is slower in SpiderMonkey, though

Reference / benchmark results?

> It's actually implemented significantly faster in every other case for objects in V8.

Any reference for that?  Just curious.

**Comment by impinball** [comment]
@dcousens It is slower in the Firefox browser I tested it right before that post via JSPerf. Although in practice, it's not really that much of a difference.

**Pull request merged**
