### PR TITLE
Added benchmarks for browsers

### PR DESCRIPTION
**Pull request by victor-homyakov**
- Added HTML page
- Refactored benchmarking code to allow its reuse

### CODE REVIEW

**Comment by dcousens** [comment]
Rather than totally bork all the existing benchmark code with browser boilerplate.  Could you just make a browserify target instead and include that in the page?

**Comment by dcousens** [comment]
ping @victor-homyakov , up to address https://github.com/JedWatson/classnames/pull/100#issuecomment-250365143

**Comment by victor-homyakov** [comment]
@dcousens could you take a look?
- added targets and static HTML page to browserify and run code in browser
- added `setTimeout`s between tests to make code more or less responsive in browser

**Comment by dcousens** [comment]
Thanks @victor-homyakov - awesome :+1:

**Pull request merged**
