### PR TITLE
add typescript contributor copyright notice

### PR DESCRIPTION
**Pull request by dcousens**
@adidahiya @JKillian @seansfkelley @mradamczyk @marvinhagemeister @ccapndave this should be enough?

As follow up to https://github.com/JedWatson/classnames/pull/103 (ref https://github.com/JedWatson/classnames/pull/103#issuecomment-426866682)

IANAL,  but,  I think this is ok.
Pinged the authors anyway...

- [x] @adidahiya 
- [x] @JKillian
- [x] @seansfkelley 
- [x] @mradamczyk
- [x] @marvinhagemeister
- [ ] @ccapndave
- [x] @bradleyayers 
- [x] @cwmacdon

### CODE REVIEW

**Comment by dcousens** [comment]
From https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5996b44c51b737b295c5ca67328ad88d0bd99644/types/classnames/index.d.ts#L1-L10

**Comment by dcousens** [comment]
@bradleyayers @cwmacdon it isn't clear to me if you two want to add your names to the list or not.
Up to you,  but submit it as a PR to this one :+1:

**Comment by cwmacdon** [comment]
I'm good, thanks! Appreciate the work to get this in.

**Comment by bradleyayers** [comment]
No need for me to be added, thanks for the heads up though!

**Comment by dcousens** [comment]
@JedWatson please ACK / merge / release

**Comment by gfx** [comment]
Thanks for telling it to me, but no need to be added.

**Comment by pd4d10** [comment]
No need for me too. Thanks!

**Comment by dcousens** [comment]
ping @JKillian @marvinhagemeister @ccapndave

**Comment by gustavohenke** [comment]
🚢

**Comment by dcousens** [comment]
@JKillian @ccapndave

**Comment by seansfkelley** [comment]
Ping @jkillian @ccapndave can you just ack so we can get this show on the road? This has been open for literally years and I keep getting pings on DefinitelyTyped for the typings there.

@dcousens do you actually need this approval? Isn't the code already public domain or whatever by virtue of being on DT?

**Comment by dcousens** [comment]
@seansfkelley it's @JedWatson's call,  he can merge at any time.
As I said before,  

> IANAL, but, I think this is ok **[as is]**

Emphasis and implied `as is` added.

**Review by JedWatson — APPROVED** [review]

**Pull request merged**
