### PR TITLE
Move benchmarks into dedicated NPM workspace

### PR DESCRIPTION
**Pull request by jonkoops**
Moves the `classnames-benchmarks` package into an NPM workspace containing all of it's own dependencies, and creates aliases for the local and last published NPM version in the package, removing the need to provide a relative path, and reducing the need for additional NPM installs.

### CODE REVIEW

**Comment by dcousens** [comment]
LGTM

**Comment by KennanChan** [comment]
It seems that this PR causes yarn to warn about "Workspaces can only be enabled in private projects.".

**Comment by jonkoops** [comment]
> It seems that this PR causes yarn to warn about "Workspaces can only be enabled in private projects.".

Don't use Yarn for this project, it has been set up to work with NPM, it's also the only package manager a lockfile is checked in for.

**Comment by KennanChan** [comment]
'Classnames' is actually an indirect dependency of my project. I managed to bypass this warning by setting `workspaces-experimental false` in yarnrc.

**Comment by dcousens** [comment]
@jonkoops the `package.json` is published though?

**Comment by jonkoops** [comment]
> the `package.json` is published though?

Correct, but workspaces should have no influence on that as far as I know. Not sure what is going on here, will do some research.

**Comment by jonkoops** [comment]
@KennanChan this should now be fixed by #350 as soon as [the release](https://github.com/JedWatson/classnames/actions/runs/7357081123) for v2.5.1 goes through.

**Pull request merged**
