### PR TITLE
Small Readme changes

### PR DESCRIPTION
**Pull request by JulienMelissas**
Consistent semicolons usage, expanded computed classes example.
Also fixed template string back-tick in example.

### CODE REVIEW

**Comment by dcousens** [comment]
@JedWatson `standard`, `semistandard`, `happiness`?

**Comment by dcousens** [comment]
@JedWatson keeping in mind happiness isn't usable atm.

**Comment by JedWatson** [comment]
Thanks @JulienMelissas - I missed this before doing a very similar edit to Readme, let me know if you think it could be made clearer than my most recent changes :)

**Comment by JulienMelissas** [comment]
No problem, your changes look good to me!

**Pull request closed without merging**
