### PR TITLE
Name the AMD module

### PR DESCRIPTION
**Pull request by impinball**
Easier than fixing merge conflicts with #47

### CODE REVIEW

**Comment by JedWatson** [comment]
Great - thanks @impinball. Glad we got back on track :grinning:

**Comment by JedWatson** [comment]
ugh, just merged this and realised there's a `+               ` at the start of the line from the previous diff. Cleaning it up now.

**Comment by impinball** [comment]
Sorry about that...my fingers are used to double quotes right now... :smile:

**Comment by dcousens** [comment]
@JedWatson you should enable protected branches,  doesn't allow merge unless tests pass ;)

**Pull request merged**
