### PR TITLE
Add de-duping fix #18

### LINKED ISSUE #18: Allow replacing of previous class names
My use case is something like `classNames('foo', { foo: false, bar: true })` should render out `class="bar"` instead of `class="foo bar"`. Should this be supported by the library or is this out of scope? I'd be glad to submit a PR if this use case is something you guys plan to support.

### PR DESCRIPTION
**Pull request by cezar-berea**
Another approach for fixing #18 by using a hash.

I know it's a bit raw, I'll apply your code style and do some perf testing when I get the chance.

### CODE REVIEW

**Comment by cezar-berea** [comment]
This one reduces perf 5 times (from 330k ops/sec to 65k ops/sec). Your call.

**Comment by 3den** [comment]
:+1: this feature is be very important for projects that use https://github.com/yahoo/atomizer

**Comment by 3den** [comment]
I hope this gets merged soon :rocket:

**Comment by longlho** [comment]
or #20  :)

**Comment by JedWatson** [comment]
Thanks for the PR @cezar-berea, we've merged #20 but this was great input to the thinking behind our final solution.

**Comment by cezar-berea** [comment]
:+1: very cool. Glad I could help. Keep up the good work.

**Pull request closed without merging**
