### PR TITLE
Accept array arguments

### PR DESCRIPTION
**Pull request by davidtheclark**
In case you are interested in accepting array arguments, as requested in https://github.com/JedWatson/classnames/issues/12, here's a PR that adds the functionality along with tests and a little documentation.

Instead of just inserting another `if` statement to `index.js` I made some significant revisions. If you don't like them, I can back out, of course. But my reasoning was that to get the intended functionality (recursive array checking) I needed (1) a named function that could be called recursively, and (2) a reliable way to test if an argument is an array. This PR uses an array-testing method I've seen some reliable people rely on, the one used by [lodash](https://github.com/lodash/lodash/blob/3.4.0/lodash.src.js#L8684) and [Underscore](http://underscorejs.org/docs/underscore.html#section-137); and since the method is equally useful to check the other types that needed checking, I thought I'd work in a simple switch statement.

Please let me know what you think, if you want anything changed, etc. Thanks!

### CODE REVIEW

**Comment by k-ori** [comment]
+1

**Comment by JedWatson** [comment]
@chenglou you made some specific changes to ensure the performance of this package, do you have any feedback on the implications of the changes @davidtheclark made?

**Comment by ZeikJT** [comment]
Why is the `checkArg` function inside of the `classNames` function? Doing that forces a new function to be created each time someone runs `classNames`, it's best if you move it out and add `classes` to the params. It doesn't need anything else from scope so it should be an easy change.

Also, `hasOwnProperty` is relatively expensive, it might be more performant to use `Object.keys`

**Comment by JedWatson** [comment]
This functionality was added along with a major speed improvement in #16

**Pull request closed without merging**
