### PR TITLE
Added context for use with bind

### PR DESCRIPTION
**Pull request by blia**
proposal #56

### CODE REVIEW

**Comment by dcousens** [comment]
Tentative NACK,  out of scope and probably has performance implications.

**Comment by JedWatson** [comment]
@blia thanks - very glad to have first class support for `css-modules`.

As discussed in #56 I think we should expose this as `classnames/bind` - would you mind making this change please? We'll need test coverage too.

Also if you could add the examples + usage notes for `css-modules` to the readme that would be great.

**Comment by blia** [comment]
Hi @JedWatson. OK, I'll do it.

**Comment by blia** [comment]
Hi. I'm just forked css-modules/webpack-demo and added `classnames/bind` to all demos.
diff - https://github.com/blia/webpack-demo/commit/ef29e78ba11f91531cecd6bbc2d16161f01bdd47
demo - https://blia.github.io/webpack-demo/
The last demo shows difference between `classnames` and `classnames/bind`

**Comment by blia** [comment]
Also with this PR https://github.com/webpack/css-loader/pull/149 Using classnames/bind and css-modules will be even more pleasant and enjoyable.
Described here - https://github.com/webpack/css-loader/pull/149#issuecomment-148179191

**Comment by dcousens** [comment]
Thanks @blia :+1:

**Comment by dcousens** [comment]
@JedWatson I'll leave you to publish

**Pull request merged**
