### PR TITLE
Safer `hasOwnProperty` check

### PR DESCRIPTION
**Pull request by impinball**
Just in case someone has a weird and terrible `hasOwnProperty` class name.

### CODE REVIEW

**Comment by dcousens** [comment]
IMHO this isn't worth it,  this module wasn't designed to deal with complex objects.
I feel like this would have come up sooner if people were actually using it like this.

NACK,  but its a trivial change so I'm not bothered.

**Comment by dcousens** [comment]
IMHO this isn't worth it,  this module wasn't designed to deal with complex objects.
I feel like this would have come up sooner if people were actually using it like this.

NACK,  but its a trivial change so I'm not *that* bothered.

**Comment by dcousens** [comment]
Thanks for your enlightening comments @impinball!
Having now actually read the code changes on GitHub instead of in the dark on my phone at 2am,  I realise this change already existed in the code base!
You merely aliased the `hasOwnProperty` to avoid the look up at run time.

If you want to re-open your PR I'll merge it,  otherwise,  I'll merge them in later today.

**Comment by impinball** [comment]
@JedWatson #49

**Comment by impinball** [comment]
Also, I don't get why #36 attracted disagreement.

**Pull request closed without merging**
