### PR TITLE
Prepare for release of version 2.5.2

### PR DESCRIPTION
**Pull request by jonkoops**

### CODE REVIEW

**Comment by jonkoops** [comment]
@dcousens could you update the configuration so we can [release this version](https://github.com/JedWatson/classnames/actions/runs/7453672472)?

**Comment by dcousens** [comment]
@jonkoops seems I don't have that capability, this might be a @JedWatson call-out

**Comment by jonkoops** [comment]
@JedWatson is this something you could facilitate?

**Comment by jonkoops** [comment]
@JedWatson could you help me out here and either allow publishes from the `v2` branch, or give me permission to do so?

**Pull request merged**
